### ISSUE TITLE
suitability for ACM7005?

### ISSUE THREAD

**Issue by dagbdagb** [gregungerer/simple-linux#1]
Hi. 

Not so much an 'issue' as a question regarding how this can be used. In short, a certain CDK with lots of really ancient cruft was recently mothballed. Good riddance.

Could this work as a starting point for a completely overhauled, (potentially community-developed) package for the hw in question? Unsure if all relevant kernel bits are upstream. 

Feel free to close/ignore, I realize this is your personal git account.

**Comment by gregungerer** [comment]
Hi,

On 28/7/23 19:22, Dag Bakke wrote:
> Hi.
> 
> Not so much an 'issue' as a question regarding how this can be used. In short, a certain CDK with lots of really ancient cruft was recently mothballed. Good riddance.
> 
> Could this work as a starting point for a completely overhauled, (potentially community-developed) package for the hw in question? Unsure if all relevant kernel bits are upstream.

No, really not a good starting point to fully support real hardware.
Simple linux is really about building and running bare minimum on emulators.

You would be better off using openwrt or buildroot for something community based.
IIRC the ACM7000 series is based on the Marvell Armada A370 SoC. That is well
supported by mainline kernels. And I know there are a few targets in openwrt
that use that SoC already.


> Feel free to close/ignore, I realize this is your personal git account.

No problem. Hope that helps.

Regards
Greg

**Comment by gregungerer** [comment]
Closing off.
